### ISSUE TITLE
Not parsing valid command

### ISSUE THREAD

**Issue by barskern** [cbourjau/cargo-with#20]
When running the following command:

```
cargo with "echo '{bin}'" -- test
```

`{bin}` is not replaced with the binary because there are `'` around it. I will make a patch to fix this now, hence hold off with the new release @cbourjau !

**Comment by cbourjau** [comment]
No need to hurry!

**Comment by barskern** [comment]
Ah okay, nice. I just wanted to make it in time to prevent you releasing a new version. Regardless, looking at the bug now.
