### ISSUE TITLE
use paths from `cargo:rustc-env=LD_LIBRARY_PATH`

### ISSUE THREAD

**Issue by problame** [cbourjau/cargo-with#30]
I use the following line in `build.rs` to add all my `LD_LIBRARY_PATH` that are *outside* of `target/`.

```rust
// make cargo run and cargo test work without setting LD_LIBRARY_PATH
println!("cargo:rustc-env=LD_LIBRARY_PATH={}", p.display());
```
This enables me to run `cargo run` and `cargo test` without setting `LD_LIBRARY_PATH`.

But `cargo-with` doesn't seem to support this flag:

```
$ cargo with gdb -- test -p mylib --release
/src/target/release/deps/mylib-932523234525: error while loading shared libraries: libfoo.so.4: cannot open shared object file: No such file or directory
```

```
(gdb) show env
...
LD_LIBRARY_PATH=/home/cs/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib
...
```

**Comment by cbourjau** [comment]
Hmm, this is quite strange. We don't fiddle with the environment variables, IIRC; we just call cargo from a sub-process that ought to inherit all variables from the parent. Do you have an educated guess what might be afoot here?

**Comment by cbourjau** [comment]
Ah, I got it: https://stackoverflow.com/a/51799351/4667084

What is happening is the following. Internally, cargo-with actually calls `cargo build` and then runs the resulting artifact explicitly. We have to do this since otherwise we would run things twice. First due to `cargo test` and then again through whatever else you wanted to have it run through. I am afraid that there is no easy way to fix this. It should work as expected if you explicitly set the variable before running `cargo-with`, does it not?

**Comment by problame** [comment]
> What is happening is the following. Internally, cargo-with actually calls cargo build and then runs the resulting artifact explicitly. We have to do this since otherwise we would run things twice. First due to cargo test and then again through whatever else you wanted to have it run through. I am afraid that there is no easy way to fix this. It should work as expected if you explicitly set the variable before running cargo-with, does it not?

Yeah it does, but my goal is to avoid requiring people to set `LD_LIBRARY_PATH`. And with the `cargo:rustc-env` feature I am _this_ close to making this a reality (`cargo test` and `cargo run` work like they do in any tutorial). 
If I may hijack this discussion: do you have any other idea how to accomplish this? any way to set `rpath` _just_ for the test binaries produced by `cargo test`?

**Comment by cbourjau** [comment]
I'm afraid I don't have a good idea right now. Do you have a public repo? My experience with linking in Rust is that explicitly telling your users what is happening might be a good idea. For example, if you users are on different Linux distributions the paths might be different anyhow.

**Comment by problame** [comment]
The repo will be public eventually but isn't yet. It's a fork of a larger C code base that builds with autotools + libtool. I added a Rust sub-project that produces an executable (because CLIs are so nice to build in Rust) and the Rust executable needs to link against a bunch of C libraries. So these libraries are not installed on the system but instead in-tree at `../lib$project/.libs`. The `.libs` part is libtool craziness.
Anyways, thanks for following up!

**Comment by cbourjau** [comment]
Given that debugging is probably not a common operation maybe its good enough to just have the libs in a file you can `source` when needed?

**Comment by problame** [comment]
Yeah, that's the approach I took. It's just that, since the C programs use libtool, the standard way to invoke a debugger is `libtool --tag=CC --mode=execute gdb path/to/libtoolwrapperbinary` and libtool just does the right thing for you.

**Comment by cbourjau** [comment]
I'm sorry there isn't a better fix. I'll close this issue, though, since I don't see any actionable item coming out of it for this project. If there is, please feel free to re-open it!
